# Generated by Django 3.1 on 2020-08-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_role_id', models.IntegerField()),
                ('user_full_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_dob', models.DateField()),
                ('user_gender', models.CharField(blank=True, max_length=100)),
                ('user_photo', models.ImageField(upload_to='')),
                ('user_reg_date', models.DateTimeField()),
                ('user_status', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
